name: om-sims
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - numpy>=2.4
  - scipy>=1.17
  - pillow>=12.1
  - tqdm>=4.67
  - pip
  - pip:
      - spiceypy>=8.0.2
      - pyvista>=0.47.1
      - pyshtools>=4.14.1
